language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_script:
  - npm prune
  - npm run flow-install-annotations
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
